Update frontend-deploy.yml

diff --git a/.github/workflows/frontend-deploy.yml b/.github/workflows/frontend-deploy.yml
--- a/.github/workflows/frontend-deploy.yml
+++ b/.github/workflows/frontend-deploy.yml
@@ -6,26 +6,16 @@ on:
       - main
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
-
-    steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
-
-    - name: Log in to Docker Hub
-      uses: docker/login-action@v3
-      with:
-        username: ${{ secrets.DOCKER_USERNAME }}
-        password: ${{ secrets.DOCKER_PASSWORD }}
-        
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v3
-      
-    - name: Build and push Docker image
-      run: |
-        docker build -t ${{ secrets.DOCKER_USERNAME }}/libraryFrontend:latest ./libraryFrontend
-        docker push ${{ secrets.DOCKER_USERNAME }}/libraryFrontend:latest
+   docker-build:
+        runs-on: ubuntu-latest
+        steps:
+           - uses: actions/checkout@v3
+           - name: Build the Docker image
+             run: |
+                  docker build . --file Dockerfile --tag libraryFrontend
+                  docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
+                  docker tag libraryFrontend ${{secrets.DOCKER_USERNAME}}/libraryFrontend
+                  docker push ${{secrets.DOCKER_USERNAME}}/libraryFrontend && echo "✅ Deployed to Docker Hub" || ( echo "❌ Deployment to Docker Hub failed" && exit 1 )
 
   deploy:
     needs: build
