mama

diff --git a/.github/workflows/frontend-deploy.yml b/.github/workflows/frontend-deploy.yml
--- a/.github/workflows/frontend-deploy.yml
+++ b/.github/workflows/frontend-deploy.yml
@@ -12,10 +12,14 @@ jobs:
       - uses: actions/checkout@v3
       - name: Create Docker Hub repository
         run: |
-          curl -X POST -H "Content-Type: application/json" \
+          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Content-Type: application/json" \
                -H "Authorization: JWT ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}" \
                -d '{"namespace": "${{secrets.DOCKER_USERNAME}}", "name": "libraryfrontend", "is_private": false}' \
-               https://hub.docker.com/v2/repositories/
+               https://hub.docker.com/v2/repositories/)
+          if [ $RESPONSE -ne 201 ]; then
+            echo "Failed to create Docker Hub repository, status code: $RESPONSE"
+            exit 1
+          fi
       - name: List directory contents
         run: ls -R
       - name: Build the Docker image
