mama

diff --git a/.github/workflows/frontend-deploy.yml b/.github/workflows/frontend-deploy.yml
--- a/.github/workflows/frontend-deploy.yml
+++ b/.github/workflows/frontend-deploy.yml
@@ -27,7 +27,7 @@ jobs:
           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         run: |
-          docker build -f ./docker/Dockerfile .  # Specify the build context (current directory)
-          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
-          docker tag libraryfrontend $DOCKER_USERNAME/libraryfrontend
-          docker push $DOCKER_USERNAME/libraryfrontend && echo "✅ Deployed to Docker Hub" || ( echo "❌ Deployment to Docker Hub failed" && exit 1 )
+          docker build -t libraryfrontend:latest -f ./docker/Dockerfile .  # Specify the build context (current directory) and tag the built image
+          echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
+          docker tag libraryfrontend:latest $DOCKER_USERNAME/libraryfrontend:latest
+          docker push $DOCKER_USERNAME/libraryfrontend:latest && echo "✅ Deployed to Docker Hub" || ( echo "❌ Deployment to Docker Hub failed" && exit 1 )
