bitte

diff --git a/.github/workflows/frontend-deploy.yml b/.github/workflows/frontend-deploy.yml
--- a/.github/workflows/frontend-deploy.yml
+++ b/.github/workflows/frontend-deploy.yml
@@ -6,15 +6,13 @@ on:
       - main
 
 jobs:
-   docker-build:
-        runs-on: ubuntu-latest
-        steps:
-           - uses: actions/checkout@v3
-           - name: Build the Docker image
-             run: |
-                  docker build . --file ../../docker/Dockerfile --tag libraryfrontend
-                  docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
-                  docker tag libraryfrontend ${{secrets.DOCKER_USERNAME}}/libraryfrontend
-                  docker push ${{secrets.DOCKER_USERNAME}}/libraryfrontend && echo "✅ Deployed to Docker Hub" || ( echo "❌ Deployment to Docker Hub failed" && exit 1 )
-
-   
+  docker-build:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - name: Build the Docker image
+        run: |
+          docker build . --file ./docker/Dockerfile --tag libraryfrontend
+          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
+          docker tag libraryfrontend ${{secrets.DOCKER_USERNAME}}/libraryfrontend
+          docker push ${{secrets.DOCKER_USERNAME}}/libraryfrontend && echo "✅ Deployed to Docker Hub" || ( echo "❌ Deployment to Docker Hub failed" && exit 1 )
